seudireito/accounts/urls.py
# encoding=utf-8

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'registro/', views.register, name='register'),
]

seudireito/core/urls.py
# encoding=utf-8

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

seudireito/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout

from seudireito.core import views

urlpatterns = [
    url(r'^', include('seudireito.core.urls', namespace='core')),
    url(r'^entrar/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^sair/$', logout, {'next_page': 'core:index'}, name='logout'),
    url(r'^conta/', include('seudireito.accounts.urls', namespace='accounts')),
    url(r'^admin/', admin.site.urls),
]

seudireito/accounts/models.py
import re

from django.db import models
from django.utils import timezone
from django.core.mail import send_mail
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.conf import settings


class UserManager(BaseUserManager):

    def _create_user(self, username, email, password, is_staff, is_superuser, **extra_fields):
        now = timezone.now()
        
        email = self.normalize_email(email)
        user = self.model(
                 username=email,   
                 email=email,
                 is_staff=is_staff, is_active=True,
                 is_superuser=is_superuser, last_login=now,
                 date_joined=now, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email=None, password=None, **extra_fields):
        return self._create_user(username, email, password, False, False, **extra_fields)

    def create_superuser(self, username, email, password, **extra_fields):
        user=self._create_user(username, email, password, True, True, **extra_fields)
        user.is_active=True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(_('username'), max_length=255, unique=True)
    name = models.CharField(_('name'), max_length=100)
    email = models.EmailField(_('email address'), max_length=255, unique=True)
    is_company = models.BooleanField(_('company'), default=False)
    is_lawyer = models.BooleanField(_('lawyer'), default=False)
    
    is_staff = models.BooleanField(_('staff status'), default=False, help_text=_('Designates whether the user can log into this admin site.'))
    is_active = models.BooleanField(_('active'), default=True, help_text=_('Designates whether this user should be treated as active. Unselect this instead of deleting accounts.'))
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    is_trusty = models.BooleanField(_('trusty'), default=False, help_text=_('Designates whether this user has confirmed his account.'))

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name','username']

    objects = UserManager()

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
    
    def get_lawyer_profile(self):
        lawyer_profile = None
        if hasattr(self, 'lawyerprofile'):
            lawyer_profile = self.lawyerprofile
        return lawyer_profile
    
    def get_company_profile(self):
        company_profile = None
        if hasattr(self, 'companyprofile'):
            company_profile = self.companyprofile
        return company_profile

    def __str__(self):
        return self.name or email

    def get_full_name(self):
        return self.name

    def get_short_name(self):
        return str(self).split(" ")[0]

    def email_user(self, subject, message, from_email=None):
        send_mail(subject, message, from_email, [self.email])

class LawyerProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    telephone = models.CharField(_('telephone'), max_length=30)
    cpf = models.CharField(_('cpf'), max_length=15, unique=True)

class CompanyProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    activity = models.CharField(_('activity'), max_length=100)

seudireito/core/models.py
from django.db import models

# Create your models here.

seudireito/accounts/forms.py
# coding=utf-8

from django.contrib.auth.forms import UserCreationForm
from django import forms

from .models import User

class RegisterForm(forms.ModelForm):
    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirmação de Senha', widget=forms.PasswordInput)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('A confirmação de senha não está correta')
        return password2

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['name','email']

class UserAdminCreationForm(UserCreationForm):
    
    class Meta:
        model: User
        fields: ['name', 'email']

class UserAdminForm(forms.ModelForm):
    
    class Meta:
        model: User
        fields: ['name','email','username','is_active','is_staff','is_lawier','is_company']

seudireito/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.core.urlresolvers import reverse_lazy
from django.core.cache import cache

from .models import User
from .forms import UserAdminCreationForm, RegisterForm

def register(request):
    cache.clear()
    template_name = 'accounts/register.html'
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(
                email=user.email, password=form.cleaned_data['password1']
            )
            login(request, user)
            return redirect('core:index')
    else:
        form = RegisterForm()
        
    context = {
        'form': form
    }
    return render(request, template_name, context)

seudireito/core/views.py
#coding=utf-8

from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import View, TemplateView, CreateView
from django.contrib.auth import get_user_model

User = get_user_model()

def index(request):
    template_name = 'index.html'
    return render(request, template_name)

# class IndexView(TemplateView):
    
#     template_name = 'index.html'
    
# index = IndexView.as_view()

seudireito/accounts/templates/accounts/register.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block content %}

<!--Feature-area-->
<section>
    <div class="container">
        <div id="signupbox" style="margin-top:100px" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
            <div class="panel">
                <div class="panel-heading">
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        
                        {% for field in form  %}
                        <div class="form-group">
                            <label class="col-md-3 control-label">{{ field.label }}</label>
                            <div class="col-md-9">
                                {% render_field field class="form-control" %}
                            </div>
                        </div>
                        {{ field.errors }}
                        {% endfor %}
                        
                        <div class="form-group">
                            <!-- Button -->
                            <div class="col-md-offset-3 col-md-9">
                                <input type="submit" value="Cadastrar" class="btn btn-primary">
                            </div>
                        </div>
        
                    </form>
                </div>
            </div>        
        </div>
    </div>
</section>
<!--Feature-area/-->

{% endblock  %}

{% block footer %}{% endblock footer %}

seudireito/accounts/templates/accounts/register_company.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block content %}

<!--Feature-area-->
<section>
    <div class="container">
        <div id="signupbox" style="margin-top:100px" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
            <div class="panel">
                <div class="panel-heading">
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        
                        {% for field in form  %}
                        <div class="form-group">
                            <label class="col-md-3 control-label">{{ field.label }}</label>
                            <div class="col-md-9">
                                {% render_field field class="form-control" %}
                            </div>
                        </div>
                        {{ field.errors }}
                        {% endfor %}
                        
                        <div class="form-group">
                            <!-- Button -->
                            <div class="col-md-offset-3 col-md-9">
                                <input type="submit" value="Cadastrar" class="btn btn-primary">
                            </div>
                        </div>
        
                    </form>
                </div>
            </div>        
        </div>
    </div>
</section>
<!--Feature-area/-->

{% endblock  %}

seudireito/core/templates/base.html
<!doctype html>
<html class="no-js" lang="pt-br">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="author" content="Emerson Santana">
    <meta name="description" content="">
    <meta name="keywords" content="HTML,CSS,XML,JavaScript">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Title -->
    <title>{{ title }}</title>
    <!-- Place favicon.ico in the root directory -->
    <link rel="apple-touch-icon" href="{% static 'colid/images/apple-touch-icon.png' %}">
    <link rel="shortcut icon" type="image/ico" href="{% static 'colid/images/favicon.ico' %}" />
    <!-- Plugin-CSS -->
    <link rel="stylesheet" href="{% static 'colid/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'colid/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'colid/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'colid/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'colid/css/animate.css' %}">
    <!-- Main-Stylesheets -->
    <link rel="stylesheet" href="{% static 'colid/css/normalize.css' %} ">
    <link rel="stylesheet" href="{% static 'colid/style.css' %}">
    <link rel="stylesheet" href="{% static 'colid/css/responsive.css' %} ">
    <script src="{% static 'colid/js/vendor/modernizr-2.8.3.min.js' %} "></script>

    <!--[if lt IE 9]>
        <script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body data-spy="scroll" data-target="#primary-menu">

    <div class="preloader">
        <div class="sk-folding-cube">
            <div class="sk-cube1 sk-cube"></div>
            <div class="sk-cube2 sk-cube"></div>
            <div class="sk-cube4 sk-cube"></div>
            <div class="sk-cube3 sk-cube"></div>
        </div>
    </div>
    <!--Mainmenu-area-->
    <div class="mainmenu-area affix" data-spy="affix" data-offset-top="100">
        <div class="container">
            <!--Logo-->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#primary-menu">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="{% url 'core:index' %}" class="navbar-brand logo">
                    <h2>Seu Direito</h2>
                </a>
            </div>
            <!--Logo/-->
            <nav class="collapse navbar-collapse" id="primary-menu">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'core:index' %}">Home</a>
                    </li>
                    <li>
                        <a href="/#service-page">Serviços</a>
                    </li>
                    <li>
                        <a href="/#contact-page">Contato</a>
                    </li>
                
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'logout' %}">Sair</a></li>
                    {% else %}
                    <li><a href="{% url 'login' %}">Entrar</a></li>
                    {% endif %}
                    <li><a href="{% url 'accounts:register' %}">Registro</a></li>
                </ul>
            </nav>
        </div>
    </div>
    <!--Mainmenu-area/-->

    {% block content %}{% endblock %}

    {% block footer %}

    <footer class="footer-area relative sky-bg" id="contact-page">
        <div class="absolute footer-bg"></div>
        <div class="footer-top">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-sm-offset-3 text-center">
                        <div class="page-title">
                            <h2>Contact with us</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit voluptates, temporibus at, facere harum fugiat!</p>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-md-4">
                        <address class="side-icon-boxes">
                            <div class="side-icon-box">
                                <div class="side-icon">
                                    <img src="{% static 'colid/images/location-arrow.png' %}" alt="">
                                </div>
                                <p><strong>Address: </strong> Box 564, Disneyland <br />USA</p>
                            </div>
                            <div class="side-icon-box">
                                <div class="side-icon">
                                    <img src="{% static 'colid/images/phone-arrow.png' %} " alt="">
                                </div>
                                <p><strong>Telephone: </strong>
                                    <a href="callto:8801812726495">+8801812726495</a> <br />
                                    <a href="callto:8801687420471">+8801687420471</a>
                                </p>
                            </div>
                            <div class="side-icon-box">
                                <div class="side-icon">
                                    <img src=" {% static 'colid/images/mail-arrow.png' %} " alt="">
                                </div>
                                <p><strong>E-mail: </strong>
                                    <a href="mailto:youremail@example.com">youremail@example.com</a> <br />
                                    <a href="mailto:youremail@example.com">example@mail.com</a>
                                </p>
                            </div>
                        </address>
                    </div>
                    <div class="col-xs-12 col-md-8">
                        <form action="process.php" id="contact-form" method="post" class="contact-form">
                            <div class="form-double">
                                <input type="text" id="form-name" name="form-name" placeholder="Your name" class="form-control" required="required">
                                <input type="email" id="form-email" name="form-email" class="form-control" placeholder="E-mail address" required="required">
                            </div>
                            <input type="text" id="form-subject" name="form-subject" class="form-control" placeholder="Message topic">
                            <textarea name="message" id="form-message" name="form-message" rows="5" class="form-control" placeholder="Your message" required="required"></textarea>
                            <button type="sibmit" class="button">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-middle">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-sm-6 pull-right">
                        <ul class="social-menu text-right x-left">
                            <li><a href="#"><i class="ti-facebook"></i></a></li>
                            <li><a href="#"><i class="ti-twitter"></i></a></li>
                            <li><a href="#"><i class="ti-google"></i></a></li>
                            <li><a href="#"><i class="ti-linkedin"></i></a></li>
                            <li><a href="#"><i class="ti-github"></i></a></li>
                        </ul>
                    </div>
                    <div class="col-xs-12 col-sm-6">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Id corrupti architecto consequuntur, laborum quaerat sed nemo temporibus unde, beatae vel.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 text-center">
                        <p>&copy;Copyright 2018 All right resurved.  This template is made with <i class="ti-heart" aria-hidden="true"></i> by <a href="https://colorlib.com">Colorlib</a></p>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    {% endblock %}



    <!--Vendor-JS-->
    <script src="{% static 'colid/js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'colid/js/vendor/bootstrap.min.js' %} "></script>
    <!--Plugin-JS-->
    <script src="{% static 'colid/js/owl.carousel.min.js' %} "></script>
    <script src="{% static 'colid/js/contact-form.js' %} "></script>
    <script src="{% static 'colid/js/jquery.parallax-1.1.3.js' %}"></script>
    <script src="{% static 'colid/js/scrollUp.min.js' %}"></script>
    <script src="{% static 'colid/js/magnific-popup.min.js' %}"></script>
    <script src="{% static 'colid/js/wow.min.js' %}"></script>
    <!--Main-active-JS-->
    <script src="{% static 'colid/js/main.js' %}"></script>

</body>

</html>

seudireito/core/templates/index.html
{% extends 'base.html' %}


{% block content %}

    <!--Header-area-->
    <header class="header-area overlay full-height relative v-center" id="home-page">
        <div class="absolute anlge-bg"></div>
        <div class="container">
            <div class="row v-center">
                <div class="col-xs-12 col-md-7 header-text">
                    <h2>It’s all about Promoting your Business</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero ex inventore vel error quibusdam animi fugiat, doloribus dolores consectetur nulla deleniti sint blanditiis quod debitis quis vitae officiis tempora numquam.</p>
                    <a href="#" class="button white">Watch video</a>
                </div>
            </div>
        </div>
    </header>
    <!--Header-area/-->



    <!--Feature-area-->
    <section class="gray-bg section-padding" id="service-page">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-4">
                    <div class="box">
                        <div class="box-icon">
                            <img src="static/colid/images/service-icon-1.png" alt="">
                        </div>
                        <h4>EASY TO USE</h4>
                        <p>Lorem ipsum dolor sit amt, consectet adop adipisicing elit, sed do eiusmod tepo raraincididunt ugt labore.</p>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-4">
                    <div class="box">
                        <div class="box-icon">
                            <img src="static/colid/images/service-icon-2.png" alt="">
                        </div>
                        <h4>AWESOEM DESIGN</h4>
                        <p>Lorem ipsum dolor sit amt, consectet adop adipisicing elit, sed do eiusmod tepo raraincididunt ugt labore.</p>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-4">
                    <div class="box">
                        <div class="box-icon">
                            <img src="static/colid/images/service-icon-3.png" alt="">
                        </div>
                        <h4>EASY TO CUSTOMAIZE</h4>
                        <p>Lorem ipsum dolor sit amt, consectet adop adipisicing elit, sed do eiusmod tepo raraincididunt ugt labore.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--Feature-area/-->



{% endblock %}

seudireito/core/templates/login.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block content %}

<!--Feature-area-->
<section class="gray-bg section-padding">
    <div class="container">
        <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
            <div class="panel">
                <div class="panel-heading">
            
                </div>
    
                <div style="padding-top:30px" class="panel-body">
    
                    <form class="form-horizontal" method="POST">
                        {% csrf_token %}
                        {% for error in form.non_field_errors  %}
                        <div class="alert-danger alert">
                            {{ error }}
                        </div>
                        {% endfor %}
                        <div style="margin-bottom: 25px" class="input-group" {% if form.username.error %} has-error {% endif %}>
                            <span class="input-group-addon">
                                <i class="glyphicon glyphicon-envelope"></i>
                            </span>
                            {% render_field form.username class="form-control" placeholder="Email" %}
                            {% for error in form.username.errors %}
                            <span class="help-block">{{ error }}</span>
                            {% endfor %}
                        </div>
    
                        <div style="margin-bottom: 25px" class="input-group" {% if form.password.error %} has-error {% endif %}>
                            <span class="input-group-addon">
                                <i class="glyphicon glyphicon-lock"></i>
                            </span>
                            {% render_field form.password class="form-control" placeholder="Senha" %}
                            {% for error in form.password.errors %}
                            <span class="help-block">{{ error }}</span>
                            {% endfor %}
                        </div>
    
                        <div class="form-group pull-right">
                            <div class="col-sm-12 controls">
                                <input type="submit" value="Entrar" class="btn btn-primary">
                            </div>
                            <!-- Button -->
                        </div>
    
    
                        <div class="form-group">
                            <div class="col-md-12 control">
                                <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%">
                                    Ainda não tem conta?
                                    <a href="{% url 'accounts:register' %}">
                                        Crie a sua conta bem aqui!
                                    </a>
                                    <div style="float:right; font-size: 80%; position: relative;">
                                        <a href="#">Esqueceu a senha?</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
    
    
    
                </div>
            </div>
        </div>
    </div>
</section>
<!--Feature-area/-->

{% endblock  %}

{% block footer %}{% endblock  %}